spring:
  profiles:
  active:
  - dev
---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-black-dev
----
spring:
  profiles: test
  application:
    name: microservicecloud-config-black-test